server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: admin
              uri: http://localhost:8081
              predicates:
                - Path=/api/admin/**

            - id: facturacion
              uri: http://localhost:8083
              predicates:
                - Path=/api/facturas/**

            - id: monopatin
              uri: http://localhost:8084
              predicates:
                - Path=/api/monopatines/**

            - id: parada
              uri: http://localhost:8085
              predicates:
                - Path=/api/paradas/**

            - id: tarifas
              uri: http://localhost:8086
              predicates:
                - Path=/api/tarifas/**
            
            - id: viajes
              uri: http://localhost:8087
              predicates:
                - Path=/api/viajes/**

            - id: cuenta
              uri: http://localhost:8082
              predicates:
                - Path=/api/cuenta/**

            - id: usuario
              uri: http://localhost:8082
              predicates:
                - Path=/api/usuario/**

          
logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG
    '[org.springframework.web]': DEBUG