# yaml
    version: '3.8'

    services:
      mysql-usuario:
        image: mysql:8.0
        container_name: mysql_usuario
        ports:
          - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "usuarios"
        volumes:
          - mysql_usuario_data:/var/lib/mysql
        restart: always

      mysql-monopatin:
        image: mysql:8.0
        container_name: mysql_monopatin
        ports:
          - "3307:3306"
        environment:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "monopatin_db"
        volumes:
          - mysql_monopatin_data:/var/lib/mysql
        restart: always

      mysql-cuenta:
        image: mysql:8.0
        container_name: mysql_cuenta
        ports:
          - "3308:3306"
        environment:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "cuenta_db"
        volumes:
          - mysql_cuenta_data:/var/lib/mysql
        restart: always

      mysql-parada:
        image: mysql:8.0
        container_name: mysql_parada
        ports:
          - "3309:3306"
        environment:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "parada_db"
        volumes:
          - mysql_parada_data:/var/lib/mysql
        restart: always

    volumes:
      mysql_usuario_data:
      mysql_monopatin_data:
      mysql_cuenta_data:
      mysql_parada_data: