version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: contmysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "integrador3"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  mongodb:
    image: mongo:latest
    container_name: contmongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db_monopatines
    volumes:
      - mongo_data:/data/db
    restart: always

  postgresdb:
    image: postgres:latest
    container_name: contpostgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_monopatines
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql


volumes:
  mysql_data:
  mongo_data:
  postgres_data:
